[[redirects]]
  from = "/*"
  to = "/404/404.html"
  status = 404

[[headers]]
    for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''
  